# Generated by Django 3.1.3 on 2020-12-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorList',
            new_name='donor',
        ),
    ]
