# Generated by Django 3.1.3 on 2020-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
    ]
