# Generated by Django 3.1.3 on 2020-11-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='donar',
            fields=[
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=25)),
                ('Student_ID', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='loginu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
