# Generated by Django 3.1.3 on 2020-11-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201130_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorlist',
            name='home_address',
        ),
    ]
