# Generated by Django 3.1.3 on 2020-11-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_donorlist_home_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checku',
        ),
        migrations.DeleteModel(
            name='contactu',
        ),
        migrations.DeleteModel(
            name='DonorList',
        ),
        migrations.DeleteModel(
            name='loginu',
        ),
    ]
