# Generated by Django 3.1.3 on 2020-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_donorlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
