# Generated by Django 3.1.3 on 2020-12-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20201201_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorList',
        ),
    ]
