# Generated by Django 3.1.3 on 2020-12-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_delete_donorlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginu',
        ),
    ]
